# Generated by Django 2.1.7 on 2019-03-17 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ad_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='organisation',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 5, 33, 14, 523580)),
        ),
    ]
