# Generated by Django 2.1.7 on 2019-03-17 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190317_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 19, 30, 42, 951831)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 17, 19, 30, 42, 952888)),
        ),
    ]
