# Generated by Django 2.1.7 on 2019-03-18 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190318_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 18, 18, 10, 25, 284498)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 18, 10, 25, 285580)),
        ),
    ]
